a = input('Digite algo: ')
print('O tipo primitivo desse valor é?', type(a))
print('Só tem espaços?',a.isspace())
print('Só tem letras?',a.isalpha())
print('Só tem números?',a.isnumeric())
print('Tem letras maiúsculas?',a.isupper())
print('É alfanumérico?',a.isalnum())
